### ISSUE TITLE
[BUG] Validate the build ID belongs to the tested package

### ISSUE THREAD

**Issue by danmyway** [danmyway/tesar#51]
**Describe the bug**
When the `-id` is specified instead of `-ref` tesar tries to assign the referenced build ID to the payload even if the build is not of the requested package.

**To Reproduce**
Request e.g. `-id 123456` with `c2r` package.

**Expected behavior**
Tesar validates the required build ID belongs to the requested package. If not, it warns the user and exits.

**CLI Output**
```
tesar test copr c2r --dry-run -id 123456 -p mockplan -t cos8
INFO | Getting copr build info for referenced ID 123456.
INFO | Getting build ID for copr-ping version 1-1.fc20.
```

**Additional context**
Additionaly tesar fails with traceback reaching the copr API when the build does not exist anymore. Relates to #8 
```
Traceback (most recent call last):
  File "/home/ddiblik/.local/bin/tesar", line 5, in <module>
    from tesar.__main__ import main
  File "/home/ddiblik/projects/tesar/src/tesar/__main__.py", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ddiblik/projects/tesar/src/tesar/__init__.py", line 19, in main
    sys.exit(dispatch())
             ^^^^^^^^^^
  File "/home/ddiblik/projects/tesar/src/dispatch/__main__.py", line 129, in main
    info, build_reference = artifact_module.get_info(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddiblik/projects/tesar/src/dispatch/copr_api.py", line 59, in get_info
    for build_info in get_build_dictionary(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ddiblik/projects/tesar/src/dispatch/copr_api.py", line 86, in get_build_dictionary
    timestamp_str = build.source_package["version"].split(".")[3]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by danmyway** [comment]
resolved by #35
